I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    menu:
TypeError: 'NoneType' object has no attribute '__getitem__'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 60, in script
    menu:
  File "D:\RenPy\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 1631, in execute
    next_node(self.items[choice][2][0])
TypeError: 'NoneType' object has no attribute '__getitem__'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
MyGame 1.0
Wed Mar 25 09:05:15 2020
